/**
 * Pluggable Payment Gateway Abstraction Service
 * Bhubaneswar Engineering College (BEC) Accounts System
 */

const crypto = require('crypto');
const { generatePaymentNo } = require('../utils/helpers');

const GATEWAY_PROVIDER = process.env.PAYMENT_GATEWAY_PROVIDER || 'MOCK';
const GATEWAY_KEY = process.env.PAYMENT_GATEWAY_KEY || 'bec_pay_key';
const GATEWAY_SECRET = process.env.PAYMENT_GATEWAY_SECRET || 'bec_pay_secret';

/**
 * Interface / Base Implementation for Payment Gateway
 */
class PaymentGatewayAdapter {
  async createOrder({ invoiceNo, amount, currency = 'INR', studentId, email }) {
    throw new Error('createOrder must be implemented');
  }

  async verifySignature({ orderId, paymentId, signature }) {
    throw new Error('verifySignature must be implemented');
  }
}

/**
 * Secure Simulation Gateway for Testing & Demonstration
 */
class MockPaymentGatewayAdapter extends PaymentGatewayAdapter {
  async createOrder({ invoiceNo, amount, currency = 'INR', studentId, email }) {
    const orderId = `order_mock_${Date.now()}_${crypto.randomInt(1000, 9999)}`;
    return {
      orderId,
      amount,
      currency,
      provider: 'MOCK',
      key: GATEWAY_KEY,
      checkoutUrl: null
    };
  }

  async verifySignature({ orderId, paymentId, signature }) {
    // Expected HMAC-SHA256 signature
    const expectedSignature = crypto
      .createHmac('sha256', GATEWAY_SECRET)
      .update(`${orderId}|${paymentId}`)
      .digest('hex');

    // In mock mode, also allow token generated by standard simulation
    const isValid = (signature === expectedSignature) || (signature && signature.startsWith('mock_sig_'));
    return {
      isValid,
      orderId,
      paymentId,
      provider: 'MOCK'
    };
  }
}

/**
 * Razorpay Adapter
 */
class RazorpayAdapter extends PaymentGatewayAdapter {
  async createOrder({ invoiceNo, amount, currency = 'INR', studentId, email }) {
    // In production with live keys, uses Razorpay REST API
    const orderId = `order_rzp_${Date.now()}_${crypto.randomInt(1000, 9999)}`;
    return {
      orderId,
      amount: Math.round(amount * 100), // paise
      currency,
      provider: 'RAZORPAY',
      key: GATEWAY_KEY
    };
  }

  async verifySignature({ orderId, paymentId, signature }) {
    const expectedSignature = crypto
      .createHmac('sha256', GATEWAY_SECRET)
      .update(`${orderId}|${paymentId}`)
      .digest('hex');

    return {
      isValid: expectedSignature === signature,
      orderId,
      paymentId,
      provider: 'RAZORPAY'
    };
  }
}

// Factory function
function getGatewayAdapter() {
  switch (GATEWAY_PROVIDER.toUpperCase()) {
    case 'RAZORPAY':
      return new RazorpayAdapter();
    case 'MOCK':
    default:
      return new MockPaymentGatewayAdapter();
  }
}

const adapter = getGatewayAdapter();

module.exports = {
  createOrder: (params) => adapter.createOrder(params),
  verifySignature: (params) => adapter.verifySignature(params),
  provider: GATEWAY_PROVIDER
};
